owner: stethoscope-js
repo: status
user-agent: stethoscope-js
sites:
  - name: Stethoscope Docs
    url: https://stethoscope.js.org
  - name: Stethoscope Embed
    url: https://stethoscope.js.org/embed/?repo=AnandChowdhary%2Flife&api=rescuetime-time-tracking&latest=top-overview.weeks
assignees:
  - AnandChowdhary
status-website:
  baseUrl: /status
  logoUrl: https://stethoscope.js.org/branding/stethoscope-icon.svg
  name: Stethoscope
  navbar:
    - title: Status
      href: /
    - title: Stethoscope Home
      href: https://stethoscope.js.org
    - title: GitHub
      href: https://github.com/stethoscope-js
