name: Summary CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:
jobs:
  release:
    name: Generate README
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Update response time
        uses: upptime/uptime-monitor@master
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          SECRET_SITE: ${{ secrets.SECRET_SITE }}
